import Head from "next/head";
import Image from "next/image";
import Comp1 from "../components/Comp1";
import Comp2 from "../components/Comp2";
import styles from "../styles/Home.module.css";
import { useAppContext } from "../components/state/AppContext";
import { useDispatchContext } from "../components/state/AppContext";

export default function Home() {
  const context_app = useAppContext();
  const dispatch_app = useDispatchContext();

  return (
    <div className={styles.container}>
      <Head>
        <title>Reducer Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Comp1 />
      <br /> <br /> <br /> <br />
      <Comp2 />
      <br /> <br /> <br /> <br />
      GLOBAL STATE {context_app.value}
    </div>
  );
}
